name: .NET Publish for Windows

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore OKDPlayer.csproj
      
    - name: Build
      run: dotnet build OKDPlayer.csproj --configuration Release --no-restore
      
    - name: Publish
      run: dotnet publish OKDPlayer.csproj --configuration Release --runtime win-x64 --self-contained true /p:PublishSingleFile=true /p:PublishTrimmed=true -o ./publish

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: win64-release
        path: ./publish
